"""fix fix  roi relationships

Revision ID: 0332f622a00a
Revises: bd65d510da05
Create Date: 2025-09-21 18:49:13.262660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0332f622a00a'
down_revision: Union[str, Sequence[str], None] = 'bd65d510da05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("traffic_logs_roi_id_fkey", "traffic_logs", type_="foreignkey")
    op.alter_column('traffic_logs', 'roi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('vehicle_history_roi_id_fkey'), 'vehicle_history', type_='foreignkey')
    op.alter_column('vehicle_history', 'roi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('vehicle_history_roi_id_fkey'), 'vehicle_history', 'rois', ['roi_id'], ['id'])
    op.alter_column('vehicle_history', 'roi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_foreign_key(op.f('traffic_logs_roi_id_fkey'), 'traffic_logs', 'rois', ['roi_id'], ['id'])
    op.alter_column('traffic_logs', 'roi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
