"""Remove vehicle_type from TrafficLog

Revision ID: 57717a54e5db
Revises: f3e85df6960c
Create Date: 2025-09-22 15:14:27.396361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57717a54e5db'
down_revision: Union[str, Sequence[str], None] = 'f3e85df6960c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_logs_vehicle_type'), table_name='traffic_logs')
    op.drop_column('traffic_logs', 'vehicle_type')
    op.add_column('vehicle_history', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_vehicle_history_vehicle_type'), 'vehicle_history', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_history_vehicle_type'), table_name='vehicle_history')
    op.drop_column('vehicle_history', 'vehicle_type')
    op.add_column('traffic_logs', sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_traffic_logs_vehicle_type'), 'traffic_logs', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###
