"""Add avg_vehicles_on_screen to traffic_logs

Revision ID: 68fda942de79
Revises: 11200c01ae99
Create Date: 2025-09-22 13:57:50.241336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fda942de79'
down_revision: Union[str, Sequence[str], None] = '11200c01ae99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_logs', sa.Column('avg_vehicles_on_screen', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic_logs', 'avg_vehicles_on_screen')
    # ### end Alembic commands ###
