"""fix ROI <-> TrafficLog relation

Revision ID: 78f2690f18d2
Revises: 0332f622a00a
Create Date: 2025-09-21 18:57:47.803282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f2690f18d2'
down_revision: Union[str, Sequence[str], None] = '0332f622a00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'traffic_logs', 'rois', ['roi_id'], ['roi_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_history_traffic_log_id_fkey'), 'vehicle_history', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_history', 'traffic_logs', ['traffic_log_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vehicle_history', 'rois', ['roi_id'], ['roi_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_trajectory_vehicle_history_id_fkey'), 'vehicle_trajectory', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_trajectory', 'vehicle_history', ['vehicle_history_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_trajectory', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_trajectory_vehicle_history_id_fkey'), 'vehicle_trajectory', 'vehicle_history', ['vehicle_history_id'], ['id'])
    op.drop_constraint(None, 'vehicle_history', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_history', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_history_traffic_log_id_fkey'), 'vehicle_history', 'traffic_logs', ['traffic_log_id'], ['id'])
    op.drop_constraint(None, 'traffic_logs', type_='foreignkey')
    # ### end Alembic commands ###
