"""fix roi relationships

Revision ID: bd65d510da05
Revises: e6fe49346930
Create Date: 2025-09-21 18:40:42.658971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd65d510da05'
down_revision: Union[str, Sequence[str], None] = 'e6fe49346930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traffic_logs', 'roi_id',
           existing_type=sa.VARCHAR(),
           type_=sa.Integer(),
           existing_nullable=True,
           postgresql_using="roi_id::integer")
    op.create_foreign_key(None, 'traffic_logs', 'rois', ['roi_id'], ['id'])
    op.alter_column('vehicle_history', 'roi_id',
           existing_type=sa.VARCHAR(),
           type_=sa.Integer(),
           existing_nullable=True,
           postgresql_using="roi_id::integer")

    op.create_foreign_key(None, 'vehicle_history', 'rois', ['roi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_history', type_='foreignkey')
    op.alter_column('vehicle_history', 'roi_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'traffic_logs', type_='foreignkey')
    op.alter_column('traffic_logs', 'roi_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
