"""create traffic tables with pgvector

Revision ID: e6fe49346930
Revises: 1096033dd465
Create Date: 2025-09-21 18:27:08.675152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'e6fe49346930'
down_revision: Union[str, Sequence[str], None] = '1096033dd465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roi_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rois_id'), 'rois', ['id'], unique=False)
    op.create_index(op.f('ix_rois_roi_id'), 'rois', ['roi_id'], unique=True)
    op.create_table('vehicle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('traffic_log_id', sa.Integer(), nullable=True),
    sa.Column('roi_id', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['traffic_log_id'], ['traffic_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_history_id'), 'vehicle_history', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_history_roi_id'), 'vehicle_history', ['roi_id'], unique=False)
    op.create_index(op.f('ix_vehicle_history_timestamp'), 'vehicle_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_history_vehicle_id'), 'vehicle_history', ['vehicle_id'], unique=False)
    op.create_table('vehicle_trajectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vehicle_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_history_id'], ['vehicle_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_trajectory_id'), 'vehicle_trajectory', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_trajectory_timestamp'), 'vehicle_trajectory', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_trajectory_vehicle_id'), 'vehicle_trajectory', ['vehicle_id'], unique=False)
    op.add_column('traffic_logs', sa.Column('roi_id', sa.String(), nullable=True))
    op.alter_column('traffic_logs', 'vehicle_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('traffic_logs', 'density',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_traffic_logs_roi_id'), 'traffic_logs', ['roi_id'], unique=False)
    op.create_index(op.f('ix_traffic_logs_timestamp'), 'traffic_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_logs_timestamp'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_roi_id'), table_name='traffic_logs')
    op.alter_column('traffic_logs', 'density',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('traffic_logs', 'vehicle_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('traffic_logs', 'roi_id')
    op.drop_index(op.f('ix_vehicle_trajectory_vehicle_id'), table_name='vehicle_trajectory')
    op.drop_index(op.f('ix_vehicle_trajectory_timestamp'), table_name='vehicle_trajectory')
    op.drop_index(op.f('ix_vehicle_trajectory_id'), table_name='vehicle_trajectory')
    op.drop_table('vehicle_trajectory')
    op.drop_index(op.f('ix_vehicle_history_vehicle_id'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_timestamp'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_roi_id'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_id'), table_name='vehicle_history')
    op.drop_table('vehicle_history')
    op.drop_index(op.f('ix_rois_roi_id'), table_name='rois')
    op.drop_index(op.f('ix_rois_id'), table_name='rois')
    op.drop_table('rois')
    # ### end Alembic commands ###
