"""Add vehicle_type to VehicleHistory table

Revision ID: f3e85df6960c
Revises: 68fda942de79
Create Date: 2025-09-22 14:34:51.821647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e85df6960c'
down_revision: Union[str, Sequence[str], None] = '68fda942de79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_logs', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_traffic_logs_vehicle_type'), 'traffic_logs', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_logs_vehicle_type'), table_name='traffic_logs')
    op.drop_column('traffic_logs', 'vehicle_type')
    # ### end Alembic commands ###
